version: "3.7"
services:
  api:
    build:
      context: ./net
      dockerfile: ../docker/net/Dockerfile
    links:
      - "postgres:database"
    ports:
      - 8081:80
      - 8082:443
    working_dir: /app
    volumes:
      - $HOME/.aspnet/https:/root/.aspnet/https
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASS: pass
      POSTGRES_DB: chamber
  postgres:
    image: postgres
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5434:5432
volumes:
  db:
    driver: local
  certs: {}